# Generated by Django 6.0.7 on 2026-08-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allow_last_seen',
            field=models.BooleanField(default=True),
        ),
    ]
